<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <SupportedOSPlatformVersion>10.0.17763</SupportedOSPlatformVersion>
    <TargetPlatformVersion>10.0.19041.0</TargetPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pick6.Core\Pick6.Core.csproj" />
    <ProjectReference Include="..\Pick6.Projection\Pick6.Projection.csproj" />
  </ItemGroup>

</Project>