<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <SupportedOSPlatformVersion>10.0.17763</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pick6.UI\Pick6.UI.csproj" />
    <ProjectReference Include="..\Pick6.Core\Pick6.Core.csproj" />
    <ProjectReference Include="..\Pick6.Projection\Pick6.Projection.csproj" />
  </ItemGroup>

</Project>
